services:
  - type: web
    name: garment-wms-be
    runtime: docker
    repo: https://github.com/Garment-WMS/garment-wms-be
    branch: d_dev
    plan: free
    envVars:
      - key: .env
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_USERNAME
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: TUYA_SECRET_KEY
        sync: false
      - key: TUYA_ACCESS_KEY
        sync: false
      - key: TUYA_ENDPOINT
        sync: false
      - key: BCRYPT_SALT_ROUNDS
        sync: false
      - key: JWT_REFRESH_TOKEN_EXPIRY
        sync: false
      - key: JWT_ACCESS_TOKEN_EXPIRY
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FIREBASE_MEASUREMENT_ID
        sync: false
      - key: FIREBASE_APP_ID
        sync: false
      - key: FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_AUTH_DOMAIN
        sync: false
      - key: FIREBASE_API_KEY
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PORT
        sync: false
    region: singapore
    dockerContext: .
    dockerfilePath: ./Dockerfile
version: '1'
